AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: CD Lambda Deployment for Mint Condition Project

Resources:
  ## Lambda to upload images
  MINTLF1:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: MINT_LF1_image_upload
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      CodeUri: ./lambda_functions/LF1_image_upload
      Description: 'CCBD Project: Lambda function for trading card upload'
      MemorySize: 128
      Timeout: 15
  ## Lambda to query sagemaker
  MINTLF2:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: MINT_LF2_image_detection
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      CodeUri: ./lambda_functions/LF2_image_detection
      Description: 'CCBD Project: Lambda function for trading card label prediction'
      MemorySize: 128
      Timeout: 15
  ## Lambda to query/update card
  MINTLF3:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: MINT_LF3_query_card
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      CodeUri: ./lambda_functions/LF3_query_card
      Description: 'CCBD Project: Lambda function for querying trading cards'
      MemorySize: 128
      Timeout: 15