AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: CD Lambda Deployment for Mint Condition Project

Resources:
  ## Ebay SDK Layer
  EventNotificationsSDKlayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: event-notification-nodejs-sdk
      Description: Ebay Event Notifications SDK
      ContentUri: ./lambda_layers/event-notification-nodejs-sdk
      CompatibleRuntimes:
        - nodejs12.x
        - nodejs14.x
      LicenseInfo: 'Available under the MIT-0 license.'
      RetentionPolicy: Retain
  ## Lambda to upload images
  MINTLF1:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: MINT_LF1_image_upload
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      CodeUri: ./lambda_functions/LF1_image_upload
      Description: 'CCBD Project: Lambda function for trading card upload'
      MemorySize: 128
      Timeout: 15
  ## Lambda to query sagemaker
  MINTLF2:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: MINT_LF2_image_detection
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      CodeUri: ./lambda_functions/LF2_image_detection
      Description: 'CCBD Project: Lambda function for trading card label prediction'
      MemorySize: 128
      Timeout: 15
  ## Lambda to query/update card
  MINTLF3:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: MINT_LF3_query_cards
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      CodeUri: ./lambda_functions/LF3_query_cards
      Description: 'CCBD Project: Lambda function for querying trading cards'
      MemorySize: 128
      Timeout: 15
  ## Lambda for Ebay Account Deletion Notification: https://developer.ebay.com/marketplace-account-deletion#optingOut
  MINTLF4:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: MINT_LF4_ebay_notification
      Handler: index.handler
      Runtime: nodejs14.x
      CodeUri: ./lambda_functions/LF4_ebay_notification
      Description: 'CCBD Project: Lambda function for ebay notification'
      MemorySize: 128
      Timeout: 15
      Layers:
         - !Ref EventNotificationsSDKlayer